services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8080:8080"
volumes:
  mysql-volume:
  minio_data:
