services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    image: cosmtrek/air
    ports:
      - 8080:8080
    command: sh -c "air"
volumes:
  mysql-volume:
  minio_data:
